### ISSUE TITLE
1.03 not working

### ISSUE THREAD

**Issue by jodrescher** [aaronk6/Kraken-MoneyMoney#3]
the following error occurred in MoneyMoney while fetching account:
`Kraken.lua:190: bad argument #1 to 'pairs' (table expected, got nil)`

**Comment by toabi** [comment]
I'm on `MoneyMoney version 2.3.4 (306) Beta` and manually changed the fix version of `1.03` to "2.3.5" and disabled code signing. I still get this log:

```
1> Refreshing account Kraken.
1> Web Banking Engine: Using user-supplied extension Kraken.lua version 1.03.
1> Protocol version: Web Scraping
1> Server address: https://api.kraken.com
1> Sending: POST https://api.kraken.com/0/private/Balance
1> Received: (actually valid JSON, according to jsonlint.com)
1> Adding filler to work around bug in product versions earlier than 2.3.5
1> Sending: POST https://api.kraken.com/0/public/AssetPairs
1> Received: (actually valid JSON, according to jsonlint.com)
1> Adding filler to work around bug in product versions earlier than 2.3.5
1> Kraken.lua:190: bad argument #1 to 'pairs' (table expected, got nil)
```

**Comment by wombart** [comment]
MoneyMoney Version 2.3.4 (306) Beta 
Can confirm it broke again,  with local fixVersion = '2.3.5' won't work.
Thanks

**Comment by aaronk6** [comment]
There was a change today in the response returned from `/public/AssetPairs`. This seems to break the workaround I applied yesterday.

The fee markers were set to `-0.1` yesterday, but now they’re set to `0`. I’m attaching the two files in case anybody wants to check them out.

I’ll see if I can fix this easily. If not, you will need to wait for the next MoneyMoney beta which will contain the real fix, making this hacky workaround obsolete.

[asset_pairs_2018-01-14.txt](https://github.com/aaronk6/Kraken-MoneyMoney/files/1632626/asset_pairs_2018-01-14.txt)

[asset_pairs_2018-01-15.txt](https://github.com/aaronk6/Kraken-MoneyMoney/files/1632625/asset_pairs_2018-01-15.txt)

**Comment by aaronk6** [comment]
I have a fix, I’ll post it later today.

**Comment by aaronk6** [comment]
Check out https://github.com/aaronk6/Kraken-MoneyMoney/commit/406127b421b42267d64b0dfc53a40af1e8948946, this fixes it for me.

Some background: This has something to do with the relation between the size of the JSON string and the amount of fields contained within it. Having a lot of fields with very small values triggers this the bug. Therefore, the workaround is to add some dummy data to the JSON response before parsing it (that’s what I did yesterday with Michael’s help). However, Kraken’s fee marker change from `-1` to `0` made the field values even smaller today, which caused this regression. I’ve now doubled the size of the filler to be safe. That’s a dirty hack, but luckily it’s only temporary until MoneyMoney 2.3.4 is out (which is expected to happen by March 2018).

**Comment by NewProggie** [comment]
@aaronk6 Thanks, that fixed it again for me 🥇

**Comment by cubistico** [comment]
Same here, thank you!

**Comment by zafai** [comment]
Hello sorry for opening this bug again but I got still this problem.

I removed the kraken.lua and downloaded the newest version from your git (I got the beta client installed version 306)

          Kraken.lua:190: bad argument #1 to 'pairs' (table expected, got nil)

Thank you

**Comment by cubistico** [comment]
If you run the beta, you must manually change the version in the script. Did you?

**Comment by zafai** [comment]
@cubistico thanks for that hint now it is working again.

Thank you!
