### ISSUE TITLE
 Kraken.lua:204: attempt to index local 'balances' (a nil value)

### ISSUE THREAD

**Issue by marcelloceschia** [aaronk6/Kraken-MoneyMoney#6]
```
10:50:57  Received: {"error":[]}
          Sending: POST https://api.kraken.com/0/public/AssetPairs
          Received: {"error":[],"result":{...}}
          Kraken.lua:204: attempt to index local 'balances' (a nil value)
```

**Comment by Mosher23** [comment]
same here

**Comment by saschanos** [comment]
@aaronk6, any plans to fix this?

**Comment by aaronk6** [comment]
Yes, sorry for the delay on this one. I’ll have a look on the weekend. Interestingly, the Kraken extension is working fine for myself, but with error description above I should be able to fix the issue nevertheless. Thanks for your patience!

**Comment by saschanos** [comment]
Thank you so much :).

**Comment by aaronk6** [comment]
Can you ensure that you’re on version 1.06? I looked at the error message that @marcelloceschia had posted and that’s actually from version 1.05. So this error might have been fixed already. Let me know how it goes!

**Comment by saschanos** [comment]
Version 1.06 is working for me. Maybe you can send an update to MoneyMoney, there's the old version listed :) https://moneymoney-app.com/extensions/

**Comment by aaronk6** [comment]
That’s odd, I just had a look and see the current version listed there. Can you double-check?

I’m closing this ticket since the underlying issue is solved.
